version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: duetmind_pgvector
    environment:
      POSTGRES_DB: duetmind
      POSTGRES_USER: duetmind
      POSTGRES_PASSWORD: duetmind_secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  db_data:
