# DuetMind Adaptive MLOps Parameters
# Central configuration for data pipelines and model training

# Data paths
data:
  raw: data/raw/
  processed: data/processed/
  features: data/processed/features.parquet
  labels: data/processed/labels.parquet

# Model parameters
model:
  type: RandomForestClassifier
  random_state: 42
  n_estimators: 100
  max_depth: 10
  test_size: 0.2

# Feature engineering
features:
  numerical_features:
    - age
    - mmse_score
    - education_level
  categorical_features:
    - gender
    - apoe_genotype
    - family_history
  target_column: diagnosis

# MLflow tracking
mlflow:
  experiment_name: duetmind_alzheimer_prediction
  tracking_uri: sqlite:///mlflow.db
  artifact_location: ./mlruns

# DVC configuration
dvc:
  remote_name: minio-storage
  remote_url: s3://duetmind-data
  
# Database configuration
database:
  host: localhost
  port: 5432
  database: duetmind_mlops
  schema: public

# Vector memory settings
vector:
  embedding_model: sentence-transformers/all-MiniLM-L6-v2
  dimension: 384
  similarity_threshold: 0.7

# Drift monitoring
drift:
  reference_window_days: 30
  detection_window_days: 7
  drift_threshold: 0.1