apiVersion: v1
kind: Service
metadata:
  name: {{ include "aimedres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aimedres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "aimedres.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
